ext-root = "Assets/Standard Assets/_Ext"
ext-editor-root = "Assets/Standard Assets/Editor/_ExtEditor"
ext-version = "Latest"

[ext-jsonobject]
[[ext-jsonobject.files]]
from = "Releases/${ext-version}"
to = "${ext-root}"
include = "JSONObject.*"
[[ext-jsonobject.files]]
from = "Releases/${ext-version}"
to = "${ext-editor-root}"
include = "JSONObjectEditor.*"

[ext-jsonobject-src]
[[ext-jsonobject-src.folders]]
from = "Scripts"
to = "${ext-root}/_JSONObject"
[[ext-jsonobject-src.folders]]
from = "Editor"
to = "${ext-editor-root}/_JSONObjectEditor"

