ext-root = "Assets/Standard Assets/_Ext"
ext-editor-root = "Assets/Standard Assets/Editor/_ExtEditor"

[ext-jsonobject]
requires = [
    "ext-jksonobject-src",
]

[ext-jsonobject-src]
[[ext-jsonobject-src.folders]]
from = "Scripts"
to = "${ext-root}/_jsonobject-src"
[[ext-jsonobject-src.folders]]
from = "Editor"
to = "${ext-editor-root}/_JSONObjectEditor"

